#!/usr/bin/env python3

# display a welcome message
print("The Greatest Miles Per Gallon program!")
print()

another_trip = "y"

while another_trip == "y":

    # get input from the user
    miles_driven = float(input("Enter miles driven:         "))
    gallons_used = float(input("Enter gallons of gas used:  "))
    cost_per_gallon = float(input("enter cost per gallon:   "))

    if miles_driven <= 0:
        print("Miles driven must be greater than zero. Please try again.")
    elif gallons_used <= 0:
        print("Gallons used must be greater than zero. Please try again.")
    elif cost_per_gallon <= 0:
        print("price per gallon must be more than zero. please try again.")
    else:
        # calculate and display miles per gallon
        mpg = round(miles_driven / gallons_used, 2)
        total_gas_cost = round(gallons_used * cost_per_gallon, 1)
        cost_per_mile = round(total_gas_cost / miles_driven, 1)
        print()
        print("Miles Per Gallon:          ", mpg)
        print("total gas cost:            ", total_gas_cost)
        print("cost per mile:             ", cost_per_mile)
        print()

    another_trip = input("get entries for another trip (y/n)")
    print()

print("Bye!")
